export const projects = [
    { id: 1, title: "A Graphical-Authentication-User-System-Experience (GAUSX)", language: "PHP & JavaScript", animate: "fadeInLeft", image: "images/gaux.png", link: "https://www.uhome.com.ng", select: "php", iframe: "https://www.youtube.com/embed/3gFlq1XNztY?si=Whzf_iSWxPcLfEjS", description: "This innovative web-based authentication system offers users the option to create a more secure login process by utilizing a combination of graphical and text-based passwords. Studies have indicated that people tend to remember images more effectively than text, and traditional text passwords are susceptible to hacking. By allowing users to select specific images and grid points to use as their graphical passwords, this system aims to provide a higher level of security compared to standard text passwords. This project was developed using HTML, PHP, JavaScript, JQuery, CSS and MySQL." },
    { id: 2, title: "Music Player", language: "React JS", animate: "fadeInRight", image: "images/mp3.png", link: "https://utprojectmsp.netlify.app/", select: "reactjs", iframe: "https://www.youtube.com/embed/goT1Ci_upKY?si=8Wr-UldPevCGGdRM", description: "Introducing an innovative and highly dynamic music player developed with React JS, designed to elevate your listening experience. This advanced music player application offers extensive customization options and a user-friendly interface, making it a joy to navigate. With a comprehensive suite of features, you can effortlessly play your favorite audio tracks and songs. What sets this player apart is its ability to transform the background based on the music currently playing, using the album art to create a visually engaging atmosphere that enhances your enjoyment. As you explore your playlists, you’ll also find detailed descriptions of the artists, giving you insight into their work, along with information about the album release year. This not only enriches your listening experience but also deepens your appreciation for the music. So, sit back, relax, and let this amazing music player transport you into a world of sound and visual delight. Cheers! Listen and enjoy! Introducing a unique and dynamic music player created with React JS. This advanced music player application is fully customizable and user-friendly, featuring all the essential functionalities to play audio and songs. It also changes the background according to the music currently being played, utilizing the album art for an enhanced experience. This adds a great vibe to your listening sessions. Additionally, it provides a brief description of the artist and the album's release year. Cheers! Listen and enjoy!" },
    { id: 3, title: "Project 3", language: "React JS", animate: "fadeInUp", image: "assets/UTlogo.png", link: "#!", select: "reactjs", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 4, title: "Project 4", language: "Python", animate: "fadeInButtom", image: "assets/UTlogo.png", link: "#!", select: "python", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 5, title: "Project 5", language: "Vue JS", animate: "fadeInLeft", image: "assets/UTlogo.png", link: "#!", select: "vuejs", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 6, title: "Project 6", language: "React TypeScript", animate: "fadeInRight", image: "assets/UTlogo.png", link: "#!", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 7, title: "Project 7", language: "PHP & JS", animate: "fadeInUp", image: "assets/UTlogo.png", link: "#!", select: "php", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 8, title: "Project 8", language: "Laravel PHP", animate: "fadeInButtom", image: "assets/UTlogo.png", link: "#!", select: "php", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    // add more projects here
  ];
  